# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4aPiwBFpZDTNSS3t1D5VKkvbWVRDl6Z
"""

# ==========================================================
# 🌍 AI Model Comparison for Travel Recommender Dataset
# Finds best-performing ML model + best-fit train-test ratio
# Displays accuracy graph directly
# ==========================================================

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

# ==========================================================
# 1️⃣ Load and Preprocess Dataset
# ==========================================================
print("📂 Loading and preprocessing dataset...")
data = pd.read_csv("destinations.csv", encoding="latin1")

# Remove duplicates
data.drop_duplicates(subset=["Destination", "Region"], keep="first", inplace=True)

# Select relevant columns
selected_columns = ["Destination", "Region", "Country", "Category", "Cost of Living"]
dataset = data[selected_columns].dropna()

# Encode categorical features
enc_country = LabelEncoder()
enc_category = LabelEncoder()
enc_cost = LabelEncoder()

dataset["Country_enc"] = enc_country.fit_transform(dataset["Country"])
dataset["Category_enc"] = enc_category.fit_transform(dataset["Category"])
dataset["Cost_enc"] = enc_cost.fit_transform(dataset["Cost of Living"])

# Features (X) and target (y)
X = dataset[["Country_enc", "Category_enc"]]
y = dataset["Cost_enc"]

# ==========================================================
# 2️⃣ Define Models for Evaluation
# ==========================================================
models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(random_state=42),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Support Vector Machine": SVC(),
    "Naive Bayes": GaussianNB(),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

# ==========================================================
# 3️⃣ Evaluate Across Different Train-Test Ratios
# ==========================================================
ratios = [0.1, 0.2, 0.25, 0.3, 0.4]
results = []

print("\n⚙️ Evaluating models across different ratios...")
for ratio in ratios:
    for name, model in models.items():
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=ratio, random_state=42)
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        results.append({
            "Model": name,
            "Test Ratio": ratio,
            "Accuracy": round(acc * 100, 2)
        })

results_df = pd.DataFrame(results)
print("\n📊 Model Performance Summary (Top 10):")
print(results_df.sort_values(by="Accuracy", ascending=False).head(10))

# ==========================================================
# 4️⃣ Find Best Model + Best-Fit Ratio
# ==========================================================
best_result = results_df.loc[results_df["Accuracy"].idxmax()]
best_model_name = best_result["Model"]
best_ratio = best_result["Test Ratio"]
best_accuracy = best_result["Accuracy"]

print("\n✅ Best-Performing Model Found:")
print(f"🔹 Model: {best_model_name}")
print(f"🔹 Best Fit Train-Test Ratio: {best_ratio}")
print(f"🔹 Accuracy: {best_accuracy}%")

# ==========================================================
# 5️⃣ Visualization (Show Directly)
# ==========================================================
print("\n📈 Displaying accuracy comparison chart...")

plt.figure(figsize=(10, 6))
for name in models.keys():
    subset = results_df[results_df["Model"] == name]
    plt.plot(subset["Test Ratio"], subset["Accuracy"], marker="o", label=name)

plt.title("Model Accuracy vs Train-Test Split Ratio", fontsize=14)
plt.xlabel("Test Ratio", fontsize=12)
plt.ylabel("Accuracy (%)", fontsize=12)
plt.legend(loc="best", fontsize=9)
plt.grid(True)
plt.tight_layout()
plt.show()  # 👈 Directly show the graph window